### ISSUE TITLE
DFU Updates

### ISSUE THREAD

**Issue by xan-m** [xan-m/Infini-iOS#1]
DFU updates need to be implemented in app

**Comment by mhv75** [comment]
Have a look at the Nordic semiconductor repositories. iOS did libs are there as well as sample apps like that implement it

**Comment by xan-m** [comment]
That's exactly what I'm implementing right now! Probably would have been pushed and merged a lot sooner if it didn't spiral into a whole UI overhaul, but the project will be all the better for it.

Thanks for the tip anyway!

**Comment by mhv75** [comment]
Ah, the pitfalls of the UI rabbit hole.
