### ISSUE TITLE
Change default Status view information

### ISSUE THREAD

**Issue by onigiri070** [xan-m/Infini-iOS#13]
I think it could be nice to give the user the option to choose which data and graph are loaded by default in the Status view of the app. 

For example, instead of always loading heart rate information, the user could set the Status view to display the battery level by default.

**Comment by xan-m** [comment]
That's a great idea, thanks for the suggestion! There's two ways to go about that: an explicitly-set user preference, or have the app remember which graph was open when the app was last used, and return to that same graph. 

The former allows a little more granular control for the user, but the latter might achieve a similar goal while being a little less hands-on for the user.

Thoughts on that?

**Comment by onigiri070** [comment]
I think having it remember is they way to go while there are so few metrics to change between. If the status view becomes more complex it may be good to make it a granular control setting at that point.

**Comment by xan-m** [comment]
I agree, and also I think adding a ton of settings for a functionally simple application is just adding complexity for no reason. Added to my to-do list!

**Comment by xan-m** [comment]
The next beta version on TestFlight (0.8.5, coming very soon) will remember the last used chart and open to that chart by default.

Marking as complete for now, but will open a separate issue for granular controls later when graph complexity increases.
