### ISSUE TITLE
Debug information view - **Opinions wanted!**

### ISSUE THREAD

**Issue by xan-m** [xan-m/Infini-iOS#18]
I've added a branch to create a debug view that BLE logs will print to, and I can add DFU logs and internal application logs as well. I started this to try to glean some information from error messages about the BLE issues that InfiniTime is currently grappling with. That turned out not to be super helpful, and I'm not sure how important this feature will be for the average user, so I'm having trouble deciding whether to add the other logs and then merge this into main, or keep this branch separate and move on to other features.

I'm creating this issue to:
a) ask if you want this feature or if it would be a nuisance
b) open this up for public comment about any features y'all might want or any other suggestions
c) to have an issue to link the branch to for clerical purposes if I do decide to merge the changes.

It's currently implemented as a toggle in the settings for "debug mode" with a link directly under it that takes you to the log view. It doesn't appear anywhere on the main views of the app or in the sidebar, so it's pretty out of the way for those who are not interested in it.

**Comment by bhibb** [comment]
I think more information is always helpful! Wouldn’t be a bad idea to be able to see why something broke or failed. For instance, when I try to sync the time with my pinetime using your app, I get an error message telling me it was not able to do so. Having some logs to peruse could help me debug why!

**Comment by xan-m** [comment]
That's interesting! I've opened error #31 to track this, and have some questions about that error for you there!

As for the debug mode, I'm leaning towards leaving out until much later down the road. I haven't added too many error messages to the app, and the BLE/DFU error messages are super unhelpful, so most of the data in the debug logs wouldn't be very worthwhile at the moment. As time goes on and I add more error handling to the app, I will reconsider.

**Comment by xan-m** [comment]
Debug view has been added to 0.9.1 which should be released shortly.
