### ISSUE TITLE
Code suggestion from another repo

### ISSUE THREAD

**Issue by GTechnology-biz** [xan-m/Infini-iOS#2]
I found a repo for a demo ios sdk of an app for a random smartwatch company. It's released under an Apache 2.0 license, and might help speed up things with this app.

[GoFIT SDK iOS](https://github.com/GO-LiFE/GoFIT_SDK_iOS)

**Comment by xan-m** [comment]
Thanks for the suggestion! Unfortunately, at first glance, I'm not sure that much of anything from this repo will be super relevant to how Infini-iOS is structured currently. Looks like this project was done in Objective-C with UIKit, and I'm working in Swift with SwiftUI. I'll take a closer look when I have some time and see if there's anything worth picking out.

**Comment by ocdtrekkie** [comment]
From my understanding, Swift is definitely the way forward on iOS stuff. Though this posits another good question: @xan-m, do you intend to set a license on this repo?

**Comment by xan-m** [comment]
@ocdtrekkie Oops, I thought I had already! Fixed now, thanks for the nudge!

**Comment by xan-m** [comment]
I've had a chance to look the code over and don't think I'll be pulling anything from it. Marking this issue as closed. Thank you for the suggestion!
