### ISSUE TITLE
Random Screen on Watch Face

### ISSUE THREAD

**Issue by sn3kyJ3di** [xan-m/Infini-iOS#23]
I have noticed lately that I will often look at my watch and the screen that shows up is something random like pong or the music controls.  It seems like the music controls come up more often.  Sometimes music will start playing on my phone.  I had the wake up set to lifting my wrist and I thought that might have had something to do with it but I changed it to tap and it still does it.  Then I though we'll maybe it's just me moving around but I have been sitting in a car for the last four hours and music started playing on my phone.  Not sure if this is the right place to report as it could be a firmware issue?  I updated to the latest firmware.

**Comment by xan-m** [comment]
I have experienced that as well, even when my watch isn't synced to my phone. I've seen casual reports of that in the PineTime bridged chat too.

 I quickly glanced at InfiniTime's issues and couldn't find any exact matches, but https://github.com/JF002/InfiniTime/issues/618 seems pretty close. I'd either jump in there or create a new issue if you don't feel like that adequately describes the issues you're experiencing. 

Infini-iOS has absolutely no control over the PineTime's display or what apps are open on the watch, so I don't think this is an issue for this app. I'll leave this issue open for a few days in case anyone has any further data, but I think this belongs in InfiniTime's issue list.

**Comment by xan-m** [comment]
I have double checked that this is not on my end and seen reports in the PineTime chat of other users not on iOS experiencing this issue, so I'm going to mark this issue as closed.

**Comment by sn3kyJ3di** [comment]
Thank you, I've been out of commission so I haven't had a chance to research it further.  Since I am using the IOS app, I thought I would start here, I appreciate your time.
