### ISSUE TITLE
Ability to send custom notifications 

### ISSUE THREAD

**Issue by marcozer** [xan-m/Infini-iOS#25]
That would be really great ton be able to send custom notifications to the watch, for test purpose but also for productivity as well : for instance, sending a todo list on the watch to get it stored the whole day would be awesome and quite trivial to implement as far as I understand (an automatic notifications in sent to the device on first connections, and there’s no need to use Apple proprietary tools).

*This was done with GadgetBridge while linked to an android device* :
 ![726046BE-5C77-4437-9D3C-FC5A47AE022B](https://user-images.githubusercontent.com/50965141/133981390-fc05b87d-6915-4d86-b030-01cb06ca421c.jpeg)

Thanks in advance

**Comment by xan-m** [comment]
Good idea, and yes that's definitely doable!

I'm assuming you mean a text field that you type into, press a button, and then send the text as an arbitrary notification to the watch?

**Comment by marcozer** [comment]
This is exactly what I mean !

I have also succeeded to send a custom notification from a linux desktop running Amazfish : 
`dbus-send --session --print-reply --dest=uk.co.piggz.amazfish /application uk.co.piggz.amazfish.sendAlert string:'' string:'FIRST LINE' string:'NOTIFICATION_TEXT' boolean:true`

**Comment by xan-m** [comment]
Awesome, that should be no problem! I've already got a function set up for sending notifications for the "iOS Connected!" notification, so I can connect that to a text box pretty easily for sending arbitrary notifications.

I've got a couple other things I'm working on adding right now, but I'll add this to the 0.9.0 milestone and should have it implemented soon.

Thanks again for the suggestion!

**Comment by xan-m** [comment]
This has been implemented in the commit I just pushed! Expect this feature in the 0.9.0 release, coming soon.

Marking issue as closed

![IMG_2089](https://user-images.githubusercontent.com/88455615/134566504-73039f47-0657-4e34-9215-0a54badb5303.png)
