### ISSUE TITLE
Feedback for 0.8.5

### ISSUE THREAD

**Issue by SwampRabbit** [xan-m/Infini-iOS#28]
I recently reported via TestFlight about disconnection issues if I completely close out the Inifini-iOS app, but thats not what this report is about, its to just provide some feedback for the "What to Test".

- flashing firmware from 1.3.0 to 1.4.0 worked fine, I like the updated UI changes a lot, it does really help
- the onboarding screen is very helpful, I also like this a lot, please consider keeping it as it is
- I think the clicking the "Use Current Device for Autoconnect" and "Clear Autoconnect Device" should provide some sort of response other than the current visual one, its hard to know something or what actually happened after clicking it
- Maybe changing "Use Current Device to Autoconnect" to "Autoconnect Current Device" with a toggle may help know its set, then "Clear Autoconnect Device" when pressed would untoggle it?

Keep up the awesome work, using and testing this has been great, waited so long for a iOS companion app!  I owe you a donation for making the PineTime work for my wife and I finally.

**Comment by xan-m** [comment]
Psh you don't owe me anything! Thanks for thinking of me though!

Unfortunately, if you fully close the app, the connection is terminated as well. I can control whether or not the connection is maintained when the app is in the background, but when you kill the app, you also kill the Bluetooth handler that understands how to talk to the PineTime. I don't think there's anything I can do about that, but I'll do some more research into it.

As to your bulleted points:
- I'm glad flashing went well!
- I've decided I will keep the onboarding screen, and will also have a "What's New" version of it as well with a changelog.
- Good point, and as a matter of fact I was just thinking about this last night. How about if the button was disabled and grayed out if the current device matches the autoconnect device? So when you click that button, it saves the device UUID and then grays the button out.

**Comment by SwampRabbit** [comment]
@xan-m understood about the connection termination, its a known minor inconvenience for the time being I guess, the watch keeps the time current so really thats enough for me right now.  ;)

You're solution to the Autoconnect functionality sounds like a plan to me!

BTW, feel free to close this if you'd like, or wait until you decide to do something with the Autoconnect functionality, it was mostly feedback to try and help more or less.  

If you don't close it, I'll leave it open for a week at most just for tracking purposes.

Side note: have you thought about enabling GitHub discussions, maybe doing a "Feedback" Category for each TestFlight release or other things?  Might help keep reported issues a bit more focused.

**Comment by xan-m** [comment]
Awesome, the autoconnect feedback mentioned above has been implemented and will be in 0.9.0.

I haven't really poked around github too much, I didn't even realize there was a discussions feature! I'll look into that. I'm maybe toying with the idea of moving away from GitHub actually, but I will definitely take the discussions feature into consideration when I make that choice!

Marking this issue as closed

**Comment by xan-m** [comment]
Thanks for the tip on the Discussions feature, I just set that up for v0.9.0!
