### ISSUE TITLE
Amazon Music support possible once AMS is working?

### ISSUE THREAD

**Issue by SwampRabbit** [xan-m/Infini-iOS#29]
Would it be possible to add Amazon Music support specifically on the list of integrations in the future once AMS implementation occurs?

Thank you for your consideration.

**Comment by xan-m** [comment]
As far as I understand, AMS will give the PineTime universal music controls, and allow control over whatever is playing at the moment, be it Amazon Music or a video in a browser window.

Think of it like the buttons on Bluetooth headphones or speakers. It should behave almost identical to that.

**Comment by SwampRabbit** [comment]
Great thanks for the explanation!
