### ISSUE TITLE
Step count support

### ISSUE THREAD

**Issue by hellojaccc** [xan-m/Infini-iOS#35]
It'd be really great to check my steps in companion app. 

Heart rate monitor doesn't work if pinetime's screen is off which makes it useless :(

Walk steps would be really useful in my opinion.

**Comment by xan-m** [comment]
I agree! Unfortunately InfiniTime does not broadcast the step count over BLE YET, so I have no way of getting it. As soon as that becomes available, it will be included in Infini-iOS!
