### ISSUE TITLE
TestFlight availability

### ISSUE THREAD

**Issue by Utopiah** [xan-m/Infini-iOS#8]
Hi, I don't have a Mac to compile it (but I imagine I could rely on a cloud service for that) and send it on the phone (part which I imagine can't be skipped). I understand that it is experimental software but have you considered sharing it via TestFlight to get feedback? Cheers and thanks for sharing you work.

**Comment by xan-m** [comment]
Absolutely! In order to publish to TestFlight, you have to have an apple developer license, which costs $100 and only lasts a year. I’m just trying to get it to a pretty usable beta state before buying the license. It’s getting pretty close though!

**Comment by xan-m** [comment]
TestFlight beta is now available!

https://testflight.apple.com/join/Z7u1Jxp4

**Comment by Utopiah** [comment]
Very nice, I booted my PineTime and right away it connected to Infini-iOS and displayed data, such a nice onboarding!

If you don't mind I'll share that on Twitter because that was such a smooth process!

**Comment by ocdtrekkie** [comment]
For some reason, my iPhone couldn't find my watch until I tried searching for it with my Windows PC... and then it suddenly showed up for your app on my phone. Beyond that it's worked so far!

**Comment by xan-m** [comment]
@Utopiah That would be fantastic, and I’m glad you’re enjoying it!

@ocdtrekkie I got feedback through TestFlight from someone who said they had to restart their iPhone to connect the first time, so I’m going to open an issue here about that. Glad it’s been working since though!

**Comment by Utopiah** [comment]
@xan-m DFU worked too, I was a bit scared since I just received the watch but ... I've already managed to customized it! https://twitter.com/utopiah/status/1429913638777798658 Thanks!

**Comment by xan-m** [comment]
Awesome! I held my breath on the first DFU update too, even though I was updating an unsealed unit with the recovery firmware in place. 

Thank you for the shout as well! I don’t have a big online footprint so all the signal boosting helps a ton!
